name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./taskschedule

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Run Unit Tests
        run: mvn clean test

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Test Build Docker Image
        run: docker build -t task-schedule:test .
